name: Release

on:
  workflow_run:
    branches:
      - main
    workflows:
      - Test
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: GitHub
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    outputs:
      new-release-published: ${{ steps.release.outputs.new-release-published }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Create a GitHub Release
        id: release
        uses: craigsloggett/create-github-release@afe4170133e10ece0944212d5f105035758ce840 # v1.0.24
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
